config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers, only: [:index,:show,:edit,:update] do
      member do
        get :follows, :followers, :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    post 'customers/guest_sign_in', to: 'customers#guest_sign_in', as: 'guest_sign_in'
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :conventions, only: [:index,:show]
    resources :matches, only: [:show] do
      resources :scorings, only: [:new]
    end
    resources :scorings, except: [:new] do
      resource :favorites, only: [:create, :destroy]
      resource :unfavorites, only: [:create, :destroy]
      resources :scoring_comments, only: [:create, :destroy]
    end
    resources :player_scoring, only: [:create,:update]
    resources :teams, only: [:index,:show]
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers, only: [:show,:edit,:update]
    resources :players, only: [:index,:create,:show,:edit,:update]
    resources :teams, only: [:index,:create,:show,:edit,:update]
    resources :affiliated_players, only: [:create,:edit,:update,:destroy]
    resources :conventions, only: [:index,:create,:show,:edit,:update]
    resources :participating_teams, only: [:create,:edit,:update,:destroy]
    resources :matches, only: [:index,:create,:show,:edit,:update]
    resources :competitors, only: [:create,:edit,:update,:destroy]
    resources :scorings, only: [:index,:show,:destroy] do
      resources :scoring_comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  #チームは複数の選手が所属しますが、選手は複数のチームに所属する可能性があります。
  has_many :affiliated_players
  has_many :teams, through: :affiliated_players
  accepts_nested_attributes_for :affiliated_players, allow_destroy: true
  #試合には複数の選手が出場し、選手は複数の試合に出場します。
  has_many :competitors
  has_many :matches, through: :competitors
  accepts_nested_attributes_for :competitors, allow_destroy: true

  validates :name, presence: true
  #誕生日から年齢を計算
  def age
    now = Date.today
    (now.strftime("%Y%m%d").to_i - birthday.strftime("%Y%m%d").to_i) / 10000
  end
  #検索機能
  def self.looks(word)
    @player = Player.where(["name like?", "%#{word}%"])
  end
  
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @player = Player.new
    @players = Player.page(params[:page])
  end
  
  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to request.referer
    else
      @players = Player.page(params[:page])
      render :index
    end
  end
  
  def show
    @player = Player.find(params[:id])
    @affiliated_player = AffiliatedPlayer.new
  end
  
  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to admin_players_path
    else
      render :edit
    end
  end
  
  private

  def player_params
    params.require(:player).permit(:name,:birthday,:height,:weight)
  end
  
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/views/admin/players/_index.html.erb
<table class="table table-sm table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>選手名</th>
      <th>生年月日(年齢)</th>
      <th>身長</th>
      <th>体重</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% players.each do |player| %>
      <tr>
        <td><%= player.id %></td>
        <td>
          <%= link_to admin_player_path(player.id) do %>
            <%= player.name %>
          <% end %>
        </td>
        <td>
          <% unless player.birthday == nil %>
            <%= player.birthday.strftime('%Y/%m/%d') %>
            (<%= player.age %>歳)
          <% else %>
            データ無し
          <% end %>
        </td>
        <td>
          <% unless player.height == nil %>
            <%= player.height %>cm
          <% else %>
            データ無し
          <% end %>
        </td>
        <td>
          <% unless player.weight == nil %>
            <%= player.weight %>kg
          <% else %>
            データ無し
          <% end %>
        </td>
        <td class="text-center"><%= link_to "編集する", edit_admin_player_path(player.id), class: "btn btn-sm btn-success" %></td>
      </tr>
    <% end %>
    <%= paginate players %>
  </tbody>
</table>

app/views/admin/players/edit.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">
  <strong><%= @player.name %></strong>の編集
</h3>
<div class="my-5">
  <%= form_with model: [:admin, @player] do |f| %>
    <%= render 'layouts/errors', obj: @player %>
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>選手名</th>
          <th>生年月日</th>
          <th>身長(cm)</th>
          <th>体重(kg)</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.text_field :name, :size=>"35", placeholder:"選手名" %></td>
          <td><%= f.text_field :birthday, :size=>"10", placeholder:"20220101" %></td>
          <td><%= f.text_field :height, :size=>"10", placeholder:"180" %></td>
          <td><%= f.text_field :weight, :size=>"10", placeholder:"75" %></td>
        </tr>
        <tr>
          <td colspan="3"></td>
          <td><%= f.submit "変更する", class: "ml-5 btn btn-success" %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/admin/players/index.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">選手登録・一覧ページ</h3>
<div class="my-3">
  <%= form_with model: [:admin, @player] do |f| %>
    <%= render 'layouts/errors', obj: @player %>
    <table class="table table-sm table-borderless">
      <thead>
        <tr>
          <th>選手名</th>
          <th>生年月日</th>
          <th>身長(cm)</th>
          <th>体重(kg)</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.text_field :name, :size=>"35", placeholder:"選手名" %></td>
          <td><%= f.text_field :birthday, placeholder:"20220101" %></td>
          <td><%= f.text_field :height, placeholder:"180" %></td>
          <td><%= f.text_field :weight, placeholder:"75" %></td>
          <td></td>
        </tr>
        <tr>
          <td colspan="3"></td>
          <td class="text-right"><%= f.submit "新規登録", class: "ml-5 btn btn-primary" %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>
<%= render "index", players: @players %>

app/views/admin/players/show.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">
  <strong><%= @player.name %></strong>の詳細
</h3>
<div class="row">
  <div style="width:300px;">
    <table class="table table-sm">
      <tbody>
        <tr>
          <th>id</th>
          <td><%= @player.id %></td>
        <tr>
          <th>生年月日(年齢)</th>
          <td>
            <% unless @player.birthday == nil %>
              <%= @player.birthday.strftime('%Y/%m/%d') %>
              (<%= @player.age %>歳)
            <% else %>
              データ無し
            <% end %>
          </td>
        </tr>
        <tr>
          <th>身長</th>
          <td>
            <% unless @player.height == nil %>
              <%= @player.height %>cm
            <% else %>
              データ無し
            <% end %>
          </td>
        </tr>
        <tr>
          <th>体重</th>
          <td>
            <% unless @player.weight == nil %>
              <%= @player.weight %>kg
            <% else %>
              データ無し
            <% end %>
          </td>
        </tr>
        <tr>
          <th>所属チーム</th>
          <td>
            <% if @player.teams.present? %>
              <% @player.teams.each do |team| %>
                <%= link_to admin_team_path(team.id) do %>
                  <%= team.name %><br>
                <% end %>
              <% end %>
            <% else %>
              所属無し
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="ml-3">
    <div style="width:fit-content;background-color:#e4e4e4;">所属先登録</div>
    <div class="ml-3">
      <%= form_with model: [:admin, @affiliated_player] do |f| %>
        <%= render 'layouts/errors', obj: @affiliated_player %>
        <table class="table table-sm table-borderless">
          <thead>
            <tr>
              <th>ポジション</th>
              <th>背番号</th>
              <th>チーム名</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= f.collection_select :position, AffiliatedPlayer.positions_i18n, :first, :last %></td>
              <td><%= f.number_field :uniform_number %></td>
              <td><%= f.collection_select :team_id,  Team.all, :id, :name, {include_blank: "--選択してください--"} %></td>
              <td><%= f.hidden_field :player_id, :value => @player.id %></td>
            </tr>
            <tr>
              <td colspan="2"></td>
              <td class="text-right"><%= f.submit "新規登録", class: "btn btn-primary" %></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>