config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers, only: [:index,:show,:edit,:update] do
      member do
        get :follows, :followers, :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    post 'customers/guest_sign_in', to: 'customers#guest_sign_in', as: 'guest_sign_in'
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :conventions, only: [:index,:show]
    resources :matches, only: [:show] do
      resources :scorings, only: [:new]
    end
    resources :scorings, except: [:new] do
      resource :favorites, only: [:create, :destroy]
      resource :unfavorites, only: [:create, :destroy]
      resources :scoring_comments, only: [:create, :destroy]
    end
    resources :player_scoring, only: [:create,:update]
    resources :teams, only: [:index,:show]
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers, only: [:show,:edit,:update]
    resources :players, only: [:index,:create,:show,:edit,:update]
    resources :teams, only: [:index,:create,:show,:edit,:update]
    resources :affiliated_players, only: [:create,:edit,:update,:destroy]
    resources :conventions, only: [:index,:create,:show,:edit,:update]
    resources :participating_teams, only: [:create,:edit,:update,:destroy]
    resources :matches, only: [:index,:create,:show,:edit,:update]
    resources :competitors, only: [:create,:edit,:update,:destroy]
    resources :scorings, only: [:index,:show,:destroy] do
      resources :scoring_comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/convention.rb
class Convention < ApplicationRecord
  has_many :matches, dependent: :destroy
  #大会には複数のチームが参加しますが、チームは複数の大会に参加します。
  has_many :participating_teams
  has_many :teams, through: :participating_teams
  accepts_nested_attributes_for :participating_teams, allow_destroy: true
  
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  #検索機能
  def self.looks(word)
    @convention = Convention.where(["name like?", "%#{word}%"])
  end
  
end

app/controllers/admin/conventions_controller.rb
class Admin::ConventionsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @convention = Convention.new
    @conventions = Convention.page(params[:page])
  end
  
  def create
    @convention = Convention.new(convention_params)
    if @convention.save
      redirect_to request.referer
    else
      @conventions = Convention.page(params[:page])
      render :index
    end
  end
  
  def show
    @convention = Convention.find(params[:id])
    @participating_team = ParticipatingTeam.new
    @participating_teams = ParticipatingTeam.preload(:team).where(convention_id: @convention.id)
    @matches = Match.preload(:home_team,:away_team).where(convention_id: @convention.id).order(:start_time).page(params[:page])
  end
  
  def edit
    @convention = Convention.find(params[:id])
  end

  def update
    @convention = Convention.find(params[:id])
    if @convention.update(convention_params)
      redirect_to admin_conventions_path
    else
      render :edit
    end
  end
  
  private

  def convention_params
    params.require(:convention).permit(:name,:start_date,:end_date)
  end
  
end

app/helpers/admin/conventions_helper.rb
module Admin::ConventionsHelper
end

app/views/admin/conventions/_index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>大会名</th>
      <th>開始日</th>
      <th>終了日</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% conventions.each do |convention| %>
      <tr>
        <td>
          <%= link_to admin_convention_path(convention.id) do %>
            <%= convention.name %>
          <% end %>
        </td>
        <td><%= convention.start_date.strftime('%Y/%m/%d') %></td>
        <td><%= convention.end_date.strftime('%Y/%m/%d') %></td>
        <td class="text-center"><%= link_to "編集する", edit_admin_convention_path(convention.id), class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
  <%= paginate conventions %>
</table>

app/views/admin/conventions/index.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">大会登録・一覧ページ</h3>
<div class="my-3">
  <%= form_with model: [:admin, @convention] do |f| %>
    <%= render 'layouts/errors', obj: @convention %>
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>大会名</th>
          <th>開始日</th>
          <th>終了日</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.text_field :name, :size=>"40", placeholder:"大会名" %></td>
          <td><%= f.text_field :start_date, placeholder:"20220101" %></td>
          <td><%= f.text_field :end_date, placeholder:"20221231" %></td>
          <td><%= f.submit "新規登録", class: "ml-5 btn btn-primary" %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>
<%= render "index", conventions: @conventions %>

app/views/admin/conventions/show.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">
  <strong><%= @convention.name %></strong>
</h3>
<h4 class="px-2 mb-1 ml-5" style="width:fit-content;background-color:#e4e4e4;">出場チーム登録</h3>
<div class="my-1 ml-5">
  <%= form_with model:[:admin, @participating_team] do |f| %>
    <%= render 'layouts/errors', obj: @participating_team %>
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>チーム名</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.collection_select :team_id, Team.all, :id, :name, {include_blank: "--選択してください--"} %></td>
          <td><%= f.hidden_field :convention_id, :value => @convention.id %></td>
          <td class="text-right"><%= f.submit "新規登録", class: "btn btn-primary" %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>
<h4 class="px-2 mb-3 ml-5" style="width:fit-content;background-color:#e4e4e4;">出場チーム一覧</h3>
<ul class="row">
  <% @participating_teams.each do |participating_team| %>
    <li class="ml-5 mb-1">
      <%= link_to admin_team_path(participating_team.team_id) do %>
        <%= participating_team.team.name %>
      <% end %>
      <%= link_to "編集", edit_admin_participating_team_path(participating_team), class: "btn btn-sm btn-success" %>
    </li>
  <% end %>
</ul>
<h4 class="px-2 ml-5" style="width:fit-content;background-color:#e4e4e4;">試合一覧</h4>
<table class="table table-sm table-hover">
  <thead>
    <tr>
      <th class="text-center">試合名</th>
      <th>開始日時（日本時間）</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td class="text-center">
          <%= link_to admin_match_path(match.id) do %>
            <%= match.home_team.name %> vs <%= match.away_team.name %><br>
            <% if match.home_goal == nil || match.away_goal == nil %>
              試合前
            <% else %>
              <%= match.home_goal %> - <%= match.away_goal %>
            <% end %>
          <% end %>
        </td>
        <td><%= match.start_time.strftime('%Y/%m/%d %H:%M') %></td>
        <td class="text-center"><%= link_to "編集する", edit_admin_match_path(match.id), class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>