config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers, only: [:index,:show,:edit,:update] do
      member do
        get :follows, :followers, :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    post 'customers/guest_sign_in', to: 'customers#guest_sign_in', as: 'guest_sign_in'
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :conventions, only: [:index,:show]
    resources :matches, only: [:show] do
      resources :scorings, only: [:new]
    end
    resources :scorings, except: [:new] do
      resource :favorites, only: [:create, :destroy]
      resource :unfavorites, only: [:create, :destroy]
      resources :scoring_comments, only: [:create, :destroy]
    end
    resources :player_scoring, only: [:create,:update]
    resources :teams, only: [:index,:show]
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers, only: [:show,:edit,:update]
    resources :players, only: [:index,:create,:show,:edit,:update]
    resources :teams, only: [:index,:create,:show,:edit,:update]
    resources :affiliated_players, only: [:create,:edit,:update,:destroy]
    resources :conventions, only: [:index,:create,:show,:edit,:update]
    resources :participating_teams, only: [:create,:edit,:update,:destroy]
    resources :matches, only: [:index,:create,:show,:edit,:update]
    resources :competitors, only: [:create,:edit,:update,:destroy]
    resources :scorings, only: [:index,:show,:destroy] do
      resources :scoring_comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :convention
  #試合でチームはホームチームとアウェイチームに分かれます。
  belongs_to :home_team, class_name: "Team", optional: true
  belongs_to :away_team, class_name: "Team", optional: true
  #試合には複数の選手が出場し、選手は複数の試合に出場します。
  has_many :competitors
  has_many :players, through: :competitors
  accepts_nested_attributes_for :competitors, allow_destroy: true
  has_many :scorings, dependent: :destroy
  
  validates :convention_id, presence: true
  validates :home_team_id, presence: true
  validates :away_team_id, presence: true
  validates :start_time, presence: true
  #検索機能
  def self.looks(word)
    @ids = Team.where(["name like?", "%#{word}%"]).pluck(:id)
    @match = Match.where(home_team_id: @ids).or(Match.where(away_team_id: @ids))
  end
  
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @match = Match.new
    @matches = Match.preload(:convention,:home_team,:away_team).order(:start_time).page(params[:page]).per(10)
  end
  
  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to request.referer
    else
      @matches = Match.page(params[:page]).per(10)
      render :index
    end
  end
  
  def show
    @match = Match.find(params[:id])
    @competitor = Competitor.new
    @competitors = Competitor.preload(:player).where(match_id: @match.id)
  end
  
  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    if @match.update(match_params)
      redirect_to admin_matches_path
    else
      flash[:alert] = "得点以外の情報は空白にできません。"
      redirect_to edit_admin_match_path
    end
  end
  
  private

  def match_params
    params.require(:match).permit(:name,:convention_id,:home_team_id,:away_team_id,
                                  :start_time,:home_goal,:away_goal)
  end
  
end

app/helpers/admin/matches_helper.rb
module Admin::MatchesHelper
end

app/views/admin/matches/_index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>大会名</th>
      <th class="text-center">試合名</th>
      <th>開始日時（日本時間）</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% matches.each do |match| %>
      <tr>
        <td>
          <%= link_to admin_convention_path(match.convention_id) do %>
            <%= match.convention.name %>
          <% end %>
        </td>
        <td class="text-center">
          <%= link_to admin_match_path(match.id) do %>
            <%= match.home_team.name %> vs <%= match.away_team.name %><br>
            <% if match.home_goal == nil || match.away_goal == nil %>
              試合前
            <% else %>
              <%= match.home_goal %> - <%= match.away_goal %>
            <% end %>
          <% end %>
        </td>
        <td><%= match.start_time.strftime('%Y/%m/%d %H:%M') %></td>
        <td class="text-center"><%= link_to "編集する", edit_admin_match_path(match.id), class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
  <%= paginate matches %>
</table>

app/views/admin/matches/edit.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">
  <%= @match.convention.name %><br>
  <strong><%= @match.home_team.name %> vs <%= @match.away_team.name %></strong>の試合情報編集
</h3>
<div class="my-5">
  <%= form_with model: [:admin, @match] do |f| %>
    <%= render 'layouts/errors', obj: @match %>
    <table class="table table-borderless" style="width:fit-content">
      <thead>
        <tr>
          <th>大会名</th>
          <th>開始日時（日本時間）</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><div class=""><%= f.collection_select :convention_id, Convention.all, :id, :name, {include_blank: "--選択してください--"} %></div></td>
          <td><%= f.text_field :start_time, placeholder:"20220101120000" %></td>
        </tr>
      </tbody>
    </table>
    <table class="table table-borderless" style="width:fit-content">
      <thead>
        <tr>
          <th>ホームチーム</th>
          <th>ホーム得点</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.collection_select :home_team_id, Team.all, :id, :name, {include_blank: "--選択してください--"} %></td>
          <td><%= f.number_field :home_goal %></td>
        </tr>
      </tbody>
    </table>
    <table class="table table-borderless" style="width:fit-content">
      <thead>
        <tr>
          <th>アウェイチーム</th>
          <th>アウェイ得点</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.collection_select :away_team_id, Team.all, :id, :name, {include_blank: "--選択してください--"} %></td>
          <td><%= f.number_field :away_goal %></td>
          <td><%= f.submit "変更を保存", class: "ml-5 btn btn-success" %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/admin/matches/index.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">試合登録・一覧ページ</h3>
<!--試合登録-->
<div class="my-3">
  <%= form_with model: [:admin, @match] do |f| %>
    <%= render 'layouts/errors', obj: @match %>
    <table class="table table-sm table-borderless" style="width:fit-content">
      <thead>
        <tr>
          <th>大会名</th>
          <th>開始日時（日本時間）</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><div class=""><%= f.collection_select :convention_id, Convention.all, :id, :name, {include_blank: "--選択してください--"} %></div></td>
          <td><%= f.text_field :start_time, placeholder:"20220101120000" %></td>
        </tr>
      </tbody>
    </table>
    <table class="table table-borderless" style="width:fit-content">
      <thead>
        <tr>
          <th>ホームチーム</th>
          <th>ホーム得点</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.collection_select :home_team_id, Team.all, :id, :name, {include_blank: "--選択してください--"} %></td>
          <td><%= f.number_field :home_goal %></td>
        </tr>
      </tbody>
    </table>
    <table class="table table-borderless" style="width:fit-content">
      <thead>
        <tr>
          <th>アウェイチーム</th>
          <th>アウェイ得点</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.collection_select :away_team_id, Team.all, :id, :name, {include_blank: "--選択してください--"} %></td>
          <td><%= f.number_field :away_goal %></td>
          <td><%= f.submit "新規登録", class: "ml-5 btn btn-primary" %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>
<%= render "index", matches: @matches %>

app/views/admin/matches/show.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">
  <%= @match.convention.name %><br>
  <%= @match.home_team.name %> vs <%= @match.away_team.name %>
</h3>
<%= @match.start_time.strftime('%Y/%m/%d %H:%M') %>開始
<h5 class="text-center">
  <% if @match.home_goal == nil || @match.away_goal == nil %>
    試合前
  <% else %>
    試合結果：<%= @match.home_goal %> - <%= @match.away_goal %>
  <% end %>
</h5>
<h4 class="px-2 mb-1 ml-3" style="width:fit-content;background-color:#e4e4e4;">出場選手登録</h3>
<div class="row">
  <div class="my-1 pl-5" style="width:50%">
    <%= form_with model:[:admin, @competitor] do |f| %>
      <%= render 'layouts/errors', obj: @competitor %>
      <div class="border-right border-dark pr-2">
        <h5 class="font-weight-bold">ホーム</h5>
        <table class="table table-borderless">
          <thead>
            <tr>
              <th>ポジション</th>
              <th>選手名</th>
              <th>背番号</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= f.collection_select :position, Competitor.positions_i18n, :first, :last %></td>
              <td><%= f.collection_select :player_id, @match.home_team.players.all, :id, :name, {include_blank: "--選択してください--"} %></td>
              <td><%= f.text_field :uniform_number, :size=>"1", placeholder: "1~99" %></td>
            </tr>
            <tr>
              <td><%= f.hidden_field :team_id, :value => @match.home_team.id %></td>
              <td><%= f.hidden_field :match_id, :value => @match.id %></td>
              <td><%= f.submit "新規登録", class: "btn btn-primary" %></td>
            </tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
  <div class="my-1 pl-2" style="width:50%">
    <%= form_with model:[:admin, @competitor] do |f| %>
      <%= render 'layouts/errors', obj: @competitor %>
      <div class="pl-3">
        <h5 class="font-weight-bold">アウェイ</h5>
        <table class="table table-borderless">
          <thead>
            <tr>
              <th>ポジション</th>
              <th>選手名</th>
              <th>背番号</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= f.collection_select :position, Competitor.positions_i18n, :first, :last %></td>
              <td><%= f.collection_select :player_id, @match.away_team.players.all, :id, :name, {include_blank: "--選択してください--"} %></td>
              <td><%= f.text_field :uniform_number, :size=>"1", placeholder: "1~99" %></td>
            </tr>
            <tr>
              <td><%= f.hidden_field :team_id, :value => @match.away_team.id %></td>
              <td><%= f.hidden_field :match_id, :value => @match.id %></td>
              <td><%= f.submit "新規登録", class: "btn btn-primary" %></td>
            </tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
<h4 class="px-2 mb-1 ml-3" style="width:fit-content;background-color:#e4e4e4;">出場選手一覧</h3>
<div class="row">
  <div style="width:45%">
    <table class="table table-hover">
      <thead>
        <tr>
          <th colspan="4" class="text-center"><%= @match.home_team.name %></th>
        </tr>
      </thead>
      <thead>
        <tr>
          <th>ポジション</th>
          <th>背番号</th>
          <th>選手名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @competitors.each do |competitor| %>
          <% if competitor.team_id == @match.home_team_id %>
            <tr>
              <td class="text-center"><%= competitor.position %></td>
              <td class="text-center"><%= competitor.uniform_number %></td>
              <td>
                <%= link_to admin_player_path(competitor.player.id) do %>
                  <%= competitor.player.name %>
                <% end %>
              </td>
              <td class="text-center"><%= link_to "編集する", edit_admin_competitor_path(competitor.id), class: "btn btn-success" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="ml-3" style="width:45%">
    <table class="table table-hover">
      <thead>
        <tr>
          <th colspan="4" class="text-center"><%= @match.away_team.name %></th>
        </tr>
      </thead>
      <thead>
        <tr>
          <th>ポジション</th>
          <th>背番号</th>
          <th>選手名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @competitors.each do |competitor| %>
          <% if competitor.team_id == @match.away_team_id %>
            <tr>
              <td class="text-center"><%= competitor.position %></td>
              <td class="text-center"><%= competitor.uniform_number %></td>
              <td>
                <%= link_to admin_player_path(competitor.player.id) do %>
                  <%= competitor.player.name %>
                <% end %>
              </td>
              <td class="text-center"><%= link_to "編集する", edit_admin_competitor_path(competitor.id), class: "btn btn-success" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>