config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers, only: [:index,:show,:edit,:update] do
      member do
        get :follows, :followers, :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    post 'customers/guest_sign_in', to: 'customers#guest_sign_in', as: 'guest_sign_in'
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :conventions, only: [:index,:show]
    resources :matches, only: [:show] do
      resources :scorings, only: [:new]
    end
    resources :scorings, except: [:new] do
      resource :favorites, only: [:create, :destroy]
      resource :unfavorites, only: [:create, :destroy]
      resources :scoring_comments, only: [:create, :destroy]
    end
    resources :player_scoring, only: [:create,:update]
    resources :teams, only: [:index,:show]
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers, only: [:show,:edit,:update]
    resources :players, only: [:index,:create,:show,:edit,:update]
    resources :teams, only: [:index,:create,:show,:edit,:update]
    resources :affiliated_players, only: [:create,:edit,:update,:destroy]
    resources :conventions, only: [:index,:create,:show,:edit,:update]
    resources :participating_teams, only: [:create,:edit,:update,:destroy]
    resources :matches, only: [:index,:create,:show,:edit,:update]
    resources :competitors, only: [:create,:edit,:update,:destroy]
    resources :scorings, only: [:index,:show,:destroy] do
      resources :scoring_comments, only: [:destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/scoring.rb
class Scoring < ApplicationRecord
  belongs_to :customer
  belongs_to :match
  has_many :scoring_comments, dependent: :destroy
  #複数の出場選手に採点を行いますが、出場選手は複数の採点をされます。
  has_many :player_scorings
  has_many :competitors, through: :player_scorings
  accepts_nested_attributes_for :player_scorings, allow_destroy: true
  #いいね・悪いね機能
  has_many :favorites, dependent: :destroy
  has_many :unfavorites, dependent: :destroy
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
  def unfavorited_by?(customer)
    unfavorites.exists?(customer_id: customer.id)
  end
  #並び替え機能
  scope :newer, -> {order(created_at: :desc)}
  scope :older, -> {order(created_at: :asc)}
  scope :favorites_count, -> {includes(:favorites).sort {|a,b| b.favorites.size <=> a.favorites.size}}
  scope :unfavorites_count, -> {includes(:unfavorites).sort {|a,b| b.unfavorites.size <=> a.unfavorites.size}}

  validates :match_id, uniqueness:{
    scope: [:customer_id]
  }

end

app/controllers/admin/scorings_controller.rb
class Admin::ScoringsController < ApplicationController
  before_action :authenticate_admin!
  def index
    if params[:newer]
      @scorings = Scoring.newer.page(params[:page]).per(10)
    elsif params[:older]
      @scorings = Scoring.older.page(params[:page]).per(10)
    elsif params[:favorites_count]
      @scorings_favorites = Scoring.favorites_count
      @scorings = Kaminari.paginate_array(@scorings_favorites).page(params[:page]).per(10)
    elsif params[:unfavorites_count]
      @scorings_unfavorites = Scoring.unfavorites_count
      @scorings = Kaminari.paginate_array(@scorings_unfavorites).page(params[:page]).per(10)
    else
      @scorings = Scoring.newer.page(params[:page]).per(10)
    end
  end

  def show
    @scoring = Scoring.find(params[:id])
    @scoring_comment = ScoringComment.new
  end
  
  def destroy
    @scoring = Scoring.find(params[:id])
    @scoring.destroy
    @scoring.player_scorings.destroy_all
    redirect_to admin_scorings_path
  end
end

app/helpers/admin/scorings_helper.rb
module Admin::ScoringsHelper
end

app/views/admin/scorings/index.html.erb
<h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">採点一覧ページ</h3>
<p>
  <%= link_to '新しい順', admin_scorings_path(newer: "true") %>
  |<%= link_to '古い順', admin_scorings_path(older: "true") %>
  |<%= link_to 'いいね順', admin_scorings_path(favorites_count: "true") %>
  |<%= link_to '悪いね順', admin_scorings_path(unfavorites_count: "true") %>
</p>
<table class="table table-hover">
  <thead>
    <tr>
      <th>会員名</th>
      <th>試合名</th>
      <th class="text-center">いいね数</th>
      <th class="text-center">悪いね数</th>
      <th class="text-center">コメント数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @scorings.each do |scoring| %>
      <tr>
        <td>
          <%= link_to admin_customer_path(scoring.customer.id) do %>
            <%= scoring.customer.name %>
          <% end %>
        </td>
        <td>
          <%= scoring.match.convention.name %><br>
          <%= scoring.match.home_team.name %>vs<%= scoring.match.away_team.name %>
        </td>
        <td class="text-center"><%= scoring.favorites.count %></td>
        <td class="text-center"><%= scoring.unfavorites.count %></td>
        <td class="text-center"><%= scoring.scoring_comments.count %></td>
        <td><%= link_to "Show", admin_scoring_path(scoring.id) %></td>
      </tr>
    <% end %>
    <%= paginate @scorings %>
  </tbody>
</table>

app/views/admin/scorings/show.html.erb
<div class="row">
  <h3 class="px-2" style="width:fit-content;background-color:#e4e4e4;">
    <%= link_to admin_match_path(@scoring.match.id) do %>
      <%= @scoring.match.convention.name %><br>
      <%= @scoring.match.home_team.name %> vs <%= @scoring.match.away_team.name %>
    <% end %>
    <strong> 採点内容</strong>
  </h3>
  <h4 class="ml-3 d-flex align-items-end">採点者:<%= @scoring.customer.name %></h4>
  <div class="ml-5 d-flex align-items-end">
    <%= link_to "採点削除", admin_scoring_path(@scoring), method: :delete, "data-confirm" => "本当に削除しますか？", class: "ml-2 btn btn-danger" %>
  </div>
</div>
<%= @scoring.match.start_time.strftime('%Y/%m/%d %H:%M') %>開始
<h5 class="text-center">
  <% if @scoring.match.home_goal == nil || @scoring.match.away_goal == nil %>
    試合前
  <% else %>
    試合結果：<%= @scoring.match.home_goal %> - <%= @scoring.match.away_goal %>
  <% end %>
</h5>
<h4 class="px-2 mb-1 ml-3" style="width:fit-content;background-color:#e4e4e4;">出場選手一覧</h3>
<div class="row">
  <div class="border-right pr-3" style="width:50%;">
    <table class="table table-sm table-hover">
      <thead>
        <tr>
          <th colspan="4" class="text-center"><%= @scoring.match.home_team.name %></th>
        </tr>
      </thead>
      <thead>
        <tr>
          <th>ポジション</th>
          <th>背番号</th>
          <th>選手名</th>
          <th>採点</th>
        </tr>
      </thead>
      <tbody>
        <% @scoring.player_scorings.each do |player_scoring| %>
          <% if player_scoring.competitor.team_id == @scoring.match.home_team_id %>
            <tr>
              <td class="text-center"><%= player_scoring.competitor.position %></td>
              <td class="text-center"><%= player_scoring.competitor.uniform_number %></td>
              <td><%= player_scoring.competitor.player.name %></td>
              <td><%= player_scoring.score %>
            </tr>
            <tr>
              <% if player_scoring.review.present? %>
                <td colspan="4"><%= player_scoring.review %></td>
              <% else %>
                <td colspan="4" class="text-secondary">寸評なし</td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="pl-3"style="width:50%;">
    <table class="table table-sm table-hover">
      <thead>
        <tr>
          <th colspan="4" class="text-center"><%= @scoring.match.away_team.name %></th>
        </tr>
      </thead>
      <thead>
        <tr>
          <th>ポジション</th>
          <th>背番号</th>
          <th>選手名</th>
          <th>採点</th>
        </tr>
      </thead>
      <tbody>
        <% @scoring.player_scorings.each do |player_scoring| %>
          <% if player_scoring.competitor.team_id == @scoring.match.away_team_id %>
            <tr>
              <td class="text-center"><%= player_scoring.competitor.position %></td>
              <td class="text-center"><%= player_scoring.competitor.uniform_number %></td>
              <td><%= player_scoring.competitor.player.name %></td>
              <td><%= player_scoring.score %>
            </tr>
            <tr>
              <% if player_scoring.review.present? %>
                <td colspan="4"><%= player_scoring.review %></td>
              <% else %>
                <td colspan="4" class="text-secondary">寸評なし</td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<h4 class="px-2 mb-1 ml-3" style="width:fit-content;background-color:#e4e4e4;">採点へのコメント</h3>
<div>
  <div>コメント数：<%= @scoring.scoring_comments.count %></div>
  <div style="width:fit-content;">
    <% @scoring.scoring_comments.each do |scoring_comment| %>
      <table class="table table-sm table-striped">
        <tr>
          <td style="width:80px;">
            <%= image_tag scoring_comment.customer.get_profile_image(60,40) %><br>
            <%= link_to admin_customer_path(scoring_comment.customer.id) do %>
              <%= scoring_comment.customer.name %>
            <% end %>
          </td>
          <td><%= scoring_comment.comment %></td>
          <td style="width:80px;"><%= link_to "削除", admin_scoring_scoring_comment_path(scoring_comment.scoring, scoring_comment), method: :delete, remote: true , class: "btn btn-sm btn-danger" %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>